### ISSUE TITLE
Can't find -Insecure flag

### ISSUE THREAD

**Issue by dtdono0** [Jaykul/Tunable-SSL-Validator#13]
I installed this module, restarted powershell w/admin and tried running:

$Result = Invoke-RestMethod -Uri $url -Method Get -Credential $c -Insecure

And I get:
A parameter cannot be found that matches parameter name 'Insecure'.

What is the actual usage for this?

**Comment by christiannancy** [comment]
Hi Dave,

If it's not too late, or if others struggle with this: What worked for me was to `Install-Module TunableSslValidator -Scope CurrentUser -AllowClobber` once then `Import-Module TunableSSLValidator` to make this module's cmdlet overwrite the defaults (I have to do this at each session but this is a module I use inside another module so it's not a problem). Then I was able to use the -Insecure parameter. I find this keeps my normal shell clean too.

Hope that helps!
Christian

**Comment by Jaykul** [comment]
Otherwise, you can write: `TunableSSLValidator\Invoke-RestMethod` to specifically use the one from this module
