### ISSUE TITLE
Error while importing in pre ps 5.0

### ISSUE THREAD

**Issue by gregorybleiker** [Jaykul/Tunable-SSL-Validator#6]
Hi
I'm getting errors while doing the module-import:
I think it would be a good idea to replace
if(Get-Command Export-ODataEndpointProxy)) {
with
if(Get-Command Export-ODataEndpointProxy -ErrorAction SilentlyContinue)) {
in TunableSSLValidator.psm1...

**Comment by Jaykul** [comment]
Good call :-) 
But ... that's already done?
