### ISSUE TITLE
How do you install this?

### ISSUE THREAD

**Issue by dboeke** [Jaykul/Tunable-SSL-Validator#8]

**Comment by GLubomirov** [comment]
import-module "PATHTODOWNLOADEDPACKAGE\TunableSSLValidator.psm1"

**Comment by Jaykul** [comment]
I added it to the PowerShell Gallery awhile ago, so to install it, you can

```posh
Install-Module TunableSSLValidator
```

And to use it, just 

```posh
Import-Module TunableSSLValidator
```
